### ISSUE TITLE
Dynamic URL navigation problem

### ISSUE THREAD

**Issue by buglinjo** [puikinsh/gentelella#363]
When I go to dynamic URL : `/hello/world/1` the navigation is collapsed. but when I'm in `/hello/world` it shows the real button in navigation. How can I get navigation work with dynamic URLs?

**Comment by djmetla** [comment]
Yeap! i need same

**Comment by connectnbs** [comment]
can you explain detail or screenshots. Maybe I can help.

**Comment by buglinjo** [comment]
Here are some screenshots:
![download](https://cloud.githubusercontent.com/assets/1254208/21994133/2eb92754-dbec-11e6-91db-1be4e4c48f53.png)
![download 1](https://cloud.githubusercontent.com/assets/1254208/21994134/3104e034-dbec-11e6-85c3-d846e5ff2fdb.png)

**Comment by farizluqman** [comment]
+1

**Comment by connectnbs** [comment]
when we press a navigation button the <li> will assigned a class "current page" by some script
make sure you included the scripts from the vendor folder and make sure you called on the layout.
i think you may not included select2 css and
![git](https://cloud.githubusercontent.com/assets/25150030/22277442/77b2bec4-e2e1-11e6-9976-e41eccaf6ddc.JPG)

**Comment by BootstrapKiller** [comment]
Hi! 
I was just facing the same issue but with GET variables (e.g. index.php?go=page). 

in build/js/custom.js go to line 42. There the currently selected URL gets put into a variable but before gets chopped up by split. 1st removing anchors, then removing any GET variables. This variable is later on compared with the available menu items, which get opened up on match. 
`var CURRENT_URL = window.location.href.split('#')[0].split('?')[0],`

My issue was solved by simply changing 
`split('?')[0]` to `split('&')[0]` which allowed the first argument but disregards all following. 

For your issue you may want to try a similar approach. Maybe check for numeric values and remove the last /x/ in front of this value. 

Cheers, 
André

**Comment by AndreiCN** [comment]
@buglinjo ar you still facing that issue ? If you don't you can close the ticket , if you do.. will take it further, thank you !

**Comment by cbmek** [comment]
I'm facing the same problem for a long time, and I've ignored it ever since. But finally decided to solve it, and here is my solution.

## The problem
You have left navigation with some submenus and let's say one of them is ```/users/```. So when you go to ```http://yourapp.com/users/``` it will be marked as active, and it's parent will be expanded. Everything is ok for now... but when you do to  ```http://yourapp.com/users/new/```, nothing will happen in nav, because you don't have en element for ```/users/new/```.
You want the app to highlight ad active an "upper" element (```/users/``` in this case).

## Solution

Locate that code in `custom.js`:

```
	// check active menu
	$SIDEBAR_MENU.find('a[href="' + CURRENT_URL + '"]').parent('li').addClass('current-page');

	$SIDEBAR_MENU.find('a').filter(function () {
		return this.href == CURRENT_URL;
	}).parent('li').addClass('current-page').parents('ul').slideDown(function() {
		setContentHeight();
	}).parent().addClass('active');
```

and modify it like this:

```

    // check active menu
    //$SIDEBAR_MENU.find('a[href="' + CURRENT_URL + '"]').parent('li').addClass('current-page');
    // ^^ this line is not needed since it does the same as code below... even in original code.

    var $cur_menu = $SIDEBAR_MENU.find('a').filter(function () { // find nav element with exact match
        return this.href == CURRENT_URL;
    });

    if ($cur_menu.length == 0) { // if no exact match, try to find best match
        var $cur_menu = $SIDEBAR_MENU.find('a').filter(function () {
            return CURRENT_URL.startsWith(this.href) && this.href != '';
        });

        if ($cur_menu.length > 1) { // get ONLY one with longest href as best match
            var l = 0;
            for (var i = 0; i < $cur_menu.length; i++) {
                if ($cur_menu.eq(l).attr('href').length < $cur_menu.eq(i).attr('href').length) l = i;
            }
            $cur_menu = $cur_menu.eq(l);
        }
    }

    // original code below, but executed for $cur_menu
    $cur_menu.parent('li').addClass('current-page').parents('ul').slideDown(function() {
        setContentHeight();
    }).parent().addClass('active');
```

And it works.

**Comment by AndreiCN** [comment]
We will add this one, thank you @cbmek for your contribution !

**Comment by AndreiCN** [comment]
Added.
